services:
  postgres:
    image: postgres:16-alpine
    container_name: whopaid-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: whopaid
      POSTGRES_USER: whopaid
      POSTGRES_PASSWORD: whopaid_secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U whopaid -d whopaid"]
      interval: 10s
      timeout: 5s
      retries: 6
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: whopaid-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: 3008
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN:-https://kidad.ir}
      DATABASE_URL: postgres://whopaid:whopaid_secret@postgres:5432/whopaid
      DB_SYNCHRONIZE: "false"
      DB_LOGGING: "false"
      DB_CONNECT_TIMEOUT_MS: "5000"
      EMAIL_PROVIDER: ${EMAIL_PROVIDER:-smtp}
      RESEND_API_KEY: ${RESEND_API_KEY:-}
      MAIL_FROM: ${MAIL_FROM:-no-reply@kidad.ir}
      APP_WEB_URL: ${APP_WEB_URL:-http://kidad.ir}
      EMAIL_VERIFY_TTL_MINUTES: ${EMAIL_VERIFY_TTL_MINUTES:-30}
      SMTP_HOST: ${SMTP_HOST:-host.docker.internal}
      SMTP_PORT: ${SMTP_PORT:-25}
      SMTP_HELO_NAME: ${SMTP_HELO_NAME:-mail.kidad.ir}
    command: sh -c "npm run typeorm:migration:run && npm run start"
    ports:
      - "3008:3008"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: whopaid-web
    restart: unless-stopped
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-/api}
      NODE_ENV: production
    ports:
      - "3000:3000"

volumes:
  pgdata:
