export enum Currency {
  TOMAN = 'TOMAN',
  RIAL = 'RIAL',
}

export enum SplitType {
  EQUAL = 'EQUAL',
  EXACT = 'EXACT',
  PERCENT = 'PERCENT',
  SHARE = 'SHARE',
}

export enum SettlementMethod {
  CASH = 'CASH',
  CARD = 'CARD',
  BANK = 'BANK',
  MANUAL = 'MANUAL',
}

export enum SettlementStatus {
  PENDING = 'PENDING',
  SETTLED = 'SETTLED',
}

export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
}

export enum FriendRequestStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
}

export enum InboxMessageType {
  INVITE_CREATED = 'INVITE_CREATED',
  INVITE_ACCEPTED = 'INVITE_ACCEPTED',
  INVITE_DECLINED = 'INVITE_DECLINED',
  SETTLEMENT_CREATED = 'SETTLEMENT_CREATED',
  PAYMENT_SETTLED = 'PAYMENT_SETTLED',
  FRIEND_REQUEST_CREATED = 'FRIEND_REQUEST_CREATED',
  FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
  FRIEND_REQUEST_DECLINED = 'FRIEND_REQUEST_DECLINED',
  FRIEND_ADDED_TO_GROUP = 'FRIEND_ADDED_TO_GROUP',
}
